/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   signal_handler.c                                   :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: aoshinth <aoshinth@student.hive.fi>        +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/03/19 10:44:37 by aoshinth          #+#    #+#             */
/*   Updated: 2025/03/21 14:40:58 by aoshinth         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../includes/minishell.h"

int g_sig = 0; // Definition and initialization.

/**
 * Initializes default signal handling for the shell's main prompt.
 *
 * This function sets up signal handling for the main shell prompt.
 * The SIGINT signal (generated by pressing Ctrl+C) is handled by the
 * `sigint_handler` function, allowing for graceful interruption of user
 * input without terminating the shell. The SIGQUIT signal (Ctrl+\) is ignored
 * to prevent it from causing unwanted behavior in the shell.
 * 
 * This ensures that users can safely interrupt input without affecting
 * the shell's operation.
 */
void init_sig(void)
{
	signal(SIGINT, sigint_handler);
	signal(SIGQUIT, SIG_IGN);
}

/**
 * Updates signal handling for child processes.
 *
 * This function modifies signal handling specifically for processes
 * spawned by the shell. It sets both SIGINT (generated by Ctrl+C) and
 * SIGQUIT (generated by Ctrl+\) signals to be handled by the `sig_handler2`
 * function. This change allows the shell to handle these signals properly,
 * such as displaying a message ("Quit (core dump)") when SIGQUIT is received
 * and ensuring a newline is printed when SIGINT is received.
 * 
 * This ensures that child processes behave as expected when receiving
 * interrupt signals.
 */
void sig_handler_changer(void)
{
	signal(SIGINT, sig_handler2);
	signal(SIGQUIT, sig_handler2);
}

/**
 * Resets signal handling to the default behavior.
 *
 * This function resets the signal handling for both SIGINT and SIGQUIT to
 * their default actions (SIG_DFL), which is the system's default behavior for
 * handling these signals. This is useful for child processes, as it ensures
 * they behave as standard system commands, without custom signal handling
 * applied by the shell.
 * 
 * It ensures that signals such as SIGINT and SIGQUIT are handled by the
 * default system behavior when executing external commands.
 */
void sig_reseted(void)
{
	signal(SIGINT, SIG_DFL);
	signal(SIGQUIT, SIG_DFL);
}

/**
 * Configures signal handling specifically for heredoc input.
 *
 * This function sets up signal handling for the heredoc input mode.
 * The SIGINT signal (generated by pressing Ctrl+C) is handled by the
 * `sig_handler_heredoc` function, allowing the user to gracefully interrupt
 * heredoc input without affecting the shell prompt. The SIGQUIT signal (Ctrl+\)
 * is ignored to prevent unwanted behavior while the user is interacting
 * with heredoc input.
 * 
 * This ensures that the shell handles interrupts correctly during heredoc input.
 */
void sig_heredoc(void)
{
	signal(SIGINT, sig_handler_heredoc);
	signal(SIGQUIT, SIG_IGN);
}

/**
 * Handles SIGINT during heredoc input.
 *
 * @signal: The signal number (expected to be SIGINT).
 *
 * This function is called when SIGINT (Ctrl+C) is received during heredoc input.
 * It closes the standard input file descriptor (STDIN) to stop reading from
 * the terminal and updates the global `g_sig` variable with the signal number
 * to indicate that SIGINT was received. This allows the heredoc process to
 * handle the interruption appropriately, such as terminating the input reading.
 */
void sig_handler_hd(int signal)
{
	close(STDIN_FILENO);
	g_sig = signal;
}
